const token = 
`BQCqQxxDmnTJtqLx8k2BMYT7sPuF_D-7GUyGiA-zgn-aO-Ku6aZPTjfXbuB_RYcdkwW6wne5BYBtE4zJvoxnzBWwTbuBTkwTcpS5WOKTFpKNPG8yPV9XgeQxGkKIPoJ6p5u-ihM-0-hyFkwWbc3rPU9Ye1Bcug4ZCBlc0uyh0firZu0_J9EcZsBTMUgeFws9sNaTM9rfKALgYQrMyjyXXhvtWIN0


`


export default token